# Generated by Django 2.2.19 on 2022-12-04 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20221203_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.PositiveSmallIntegerField(choices=[(1, '1 - Отвратительно'), (2, '2 - Очень плохо'), (3, '3 - Плохо'), (4, '4 - Скорее плохо'), (5, '5 - Средне'), (6, '6 - Неплохо'), (7, '7 - Скорее хорошо'), (8, '8 - Хорошо'), (9, '9 - Очень хорошо'), (10, '10 - Великолепно')]),
        ),
    ]
